config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { omniauth_callbacks: "callbacks" }

  resources :spotify, only: [:index]
  get '/collections/:collection_id/spotify/search', to: 'spotify#search', as: :search_spotify

  resources :albums, only: [:destroy] do
    collection do
      get '/:spotify_id/play', to: 'albums#play', as: 'play'
    end
  end

  resources :users, only: [:show]

  resources :collections, only: [:show, :create, :edit, :update, :destroy] do
    collection do
      get :random
    end
    post '/reorder', to: 'collections#reorder', as: :reorder
    resources :albums, only: [:create] do
      collection do
        post :create_custom
      end
    end
  end

  resources :welcome, only: [:index]

  root to: 'welcome#about'

end

app/models/album.rb
class Album < ApplicationRecord
  belongs_to :collection

  validates :name, :artist, :year, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/collection.rb
class Collection < ApplicationRecord
  belongs_to :user
  has_many :albums

  after_initialize do
    self.title ||= 'My New Tapedeck'
  end

  validates :title, presence: true

end

app/models/user.rb
class User < ApplicationRecord

  has_many :collections
  has_many :albums, through: :collections

  devise :database_authenticatable, :omniauthable, omniauth_providers: [:facebook, :twitter]

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.email = auth.info.email.present? ? auth.info.email : "user-#{auth.uid}@tapedeck.io"
      user.password = Devise.friendly_token[0,20]
      user.username = auth.info.name
    end
  end

  def can_edit_collection?(collection)
    collection.user == self
  end
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController

  def play
    album = RSpotify::Album.find(params[:spotify_id])
    @album_data = get_album_data(album)
  end

  def create
    @collection = current_user.collections.find(params[:collection_id])
    reject_request! unless @collection.user == current_user
    spotify_object = RSpotify::Album.find(params[:spotify_id])
    @album = @collection.albums.new(spotify_id: spotify_object.id, art: spotify_object.images.first['url'], name: spotify_object.name, artist: spotify_object.artists.first.name, year: get_release_year(spotify_object), position: (@collection.albums.count + 1))
    @album.save
  end

  def create_custom
    @collection = current_user.collections.find(params[:collection_id])
    reject_request! unless @collection.user == current_user
    @album = @collection.albums.new(custom: true, position: (@collection.albums.count + 1))
    @album.assign_attributes(custom_album_params)
    @album.save
    render :create
  end

  def destroy
    @album_id = params[:id]
    @album = current_user.albums.find(@album_id)
    reject_request! unless @album.collection.user == current_user
    @album.destroy
  end

  private

  def get_album_data(album)
    track_objects = album.tracks
    tracks = Hash.new
    tracks[:preview_urls] = track_objects.map(&:preview_url)
    tracks[:track_names] = track_objects.map(&:name)
    tracks[:track_artists] = track_objects.map{ |obj| obj.artists.map(&:name).to_sentence }
    {
      tracks: tracks,
      duration: 10000,
      album_name: album.name,
      album_art: album.images.first['url']
    }.to_json
  end

  def get_release_year(album)
    if album.release_date_precision == "year"
      return album.release_date
    elsif album.release_date_precision == "month"
      d = "#{album.release_date}-01"
    elsif album.release_date_precision == "day"
      d = album.release_date
    end
    d.to_date.year
  end

  def custom_album_params
    params.require(:album).permit(:name, :artist, :year)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def reject_request!
    raise "User is not authorized"
  end

  def after_sign_in_path_for(resource)
    user_path(resource)
  end
end

app/controllers/callbacks_controller.rb
class CallbacksController < Devise::OmniauthCallbacksController

  def facebook
    register_or_sign_in
  end

  def twitter
    register_or_sign_in
  end

  private

  def register_or_sign_in
    auth = request.env["omniauth.auth"]
    @user = User.from_omniauth(auth)
    sign_in_and_redirect @user
  end

end

app/controllers/collections_controller.rb
class CollectionsController < ApplicationController

  def show
    @collection = Collection.find(params[:id])
  end

  def edit
    @collection = Collection.find(params[:id])
    reject_request! unless user_signed_in? && (@collection.user == current_user)
  end

  def random
    collection = Album.all.sample.collection
    redirect_to collection_path(collection)
  end

  def create
    authenticate_user!
    @collection = current_user.collections.new
    if @collection.save
      redirect_to edit_collection_path(@collection)
    end
  end

  def update
    @collection = current_user.collections.find(params[:id])
    @collection.update_attributes(collection_params)
    redirect_to collection_path(@collection)
  end

  def destroy
    @collection = current_user.collections.find(params[:id])
    @collection.destroy
    redirect_to user_path(current_user)
  end

  def reorder
    position = 1
    collection = current_user.collections.find(params[:collection_id])
    albums = collection.albums
    ActiveRecord::Base.transaction do
      params[:album].each do |tape_id|
        t = albums.find(tape_id)
        t.update_attributes(position: position)
        position += 1
      end
    end
    render json: nil, status: :ok
  end

  private

  def collection_params
    params.require(:collection).permit(:title, :ordered)
  end
end

app/controllers/spotify_controller.rb
class SpotifyController < ApplicationController

  def search
    @collection = current_user.collections.find(params[:collection_id])
    @albums = RSpotify::Album.search(spotify_params.values.first)
    @albums = @albums.reject{ |a| !a.is_a?(RSpotify::Album) }
    @albums = @albums.map{ |a| Album.new(spotify_id: a.id, art: a.images.first['url'], name: a.name, artist: a.artists.first.name) }
  end

  private

  def spotify_params
    params.require(:spotify).permit(:query)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/albums/_album.html.erb
<div class='album-wrapper col-centered col-xs-4 col-md-2' id="album_<%= album.id %>">
  <div class='album col-xs-12'>
    <% if collection.ordered? %>
      <div class='order'>
        <h3><%= album.position %></h3>
      </div>
    <% end %>
    <div class='album-art'>
      <% unless album.custom? %>
        <%= link_to play_albums_path(album.spotify_id), remote: true do %>
          <%= render 'albums/album_overlay', album: album %>
        <% end %>
      <% end %>
      <% if defined?(edit) %>
        <div class='album-remove'>
          <%= link_to album_path(album.id), remote: true, method: :delete do %>
            <% if album.custom? %>
              <%= fa_icon 'times', class: 'remove-custom' %>
            <% else %>
              <%= fa_icon 'times' %>
            <% end %>
          <% end %>
        </div>
      <% end %>
      <% if album.custom? %>
        <div class='custom-album-info'>
          <h3><%= album.name %></h3>
          <h5><%= album.artist %></h5>
          <p><%= album.year %></p>
        </div>
        <%= image_tag 'custom-album-background.png', class: 'img-thumbnail' %>
      <% else %>
        <img class="img-thumbnail" src=<%= album.art %>>
      <% end %>
    </div>
  </div>
</div>

app/views/albums/_album_overlay.html.erb
<div class='album-overlay'>
  <div class='album-info'>
    <span class='album-name'><%= album.name %></span></br>
    <span class='album-artist'><%= album.artist %></span></br>
    <span class='album-year'><%= album.year %></span>
  </div>
</div>

app/views/albums/create.js.erb
$('#collection').append("<%= j render @album, collection: @collection, edit: true %>");
$('#new-tape').modal('toggle');

$('#reorder-script').html("<%= j render 'collections/reorder_script' %>");

app/views/albums/destroy.js.erb
var album_id = '#album_' + "<%= j @album_id.to_s %>"
$(album_id).remove();
sendOrderToServer();

app/views/albums/play.js.erb
var initializePlayerControls = function() {
  $(".stop_button").off().on('click', function () {
    end();
  });

  $(".next_button").off().on('click', function () {
    if(trackNo == maxTrackNo) {
      end();
    } else {
      skipForwards();
    }
  });

  $(".previous_button").off().on('click', function () {
    skipBackwards();
  });
}

var end = function() {
  $("#jplayer2, #jplayer1").jPlayer("clearMedia");
  $('#player').removeClass('open-slider');
  $('#menu-button').removeClass('rotate');
};

var updatePlayerInfo = function() {
  $('#player_song').text(album_data["tracks"]["track_names"][trackNo]);
  $('#player_artist').text(album_data["tracks"]["track_artists"][trackNo]);
  $('#player_album').text(album_data["album_name"]);
  $('#player_cover').css("background-image", "url(" + album_data["album_art"] + ")");
};

var skipForwards = function() {
  loadMedia();
  play();
};

var skipBackwards = function() {
  if (trackNo == 1) {
    trackNo -= 1;
  } else {
    trackNo -= 2;
  }
  loadMedia();
  play();
};

var prepareNextTrack = function() {
  if (trackNo == maxTrackNo) {
    end();
  } else {
    trackNo += 1;
    loadMedia();
  }
};

var currentPlayer = function() {
  var player;
  if (trackNo % 2 === 0) {
    player = $("#jplayer2");
  } else {
    player = $("#jplayer1");
  }
  return player;
};

var play = function() {
  updatePlayerInfo();
  $('#player').addClass('open-slider');
  $('#menu-button').addClass('rotate');
  currentPlayer().jPlayer("play");
  prepareNextTrack();
};

var loadMedia = function() {
  currentPlayer().jPlayer("setMedia", {
    m4a: album_data["tracks"]["preview_urls"][trackNo]
  });
};

//START HERE

var album_data = <%= raw json_escape(@album_data) %>;
var trackNo = 0;
var maxTrackNo = album_data["tracks"]["preview_urls"].length

$("#jplayer1, #jplayer2").jPlayer({
  timeupdate: function(event) {
    if (event.jPlayer.status.currentTime >= (album_data["duration"]/1000)) {
      play();
    }
  },
  swfPath: "/js",
  supplied: "m4a"
});

loadMedia();

initializePlayerControls();

// hack for iOS
$(currentPlayer).jPlayer("play");
$(currentPlayer).jPlayer("pause");
// -----

play();

app/views/collections/_add_model.html.erb
<div class="modal fade" id="new-tape">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Add a Tape</h4>
      </div>
      <span id='search-spotify'>
        <div class="modal-body">
          <div class='form-group search-spotify'>
            <%= form_for :spotify, url: search_spotify_path(@collection), remote: true, method: :get do |f| %>
              <%= f.text_field :query, class: "form-control", placeholder: 'Album or Artist Name' %>
              <div id='results'></div>
          </div>
        </div>
        <div class="modal-footer">
            <%= f.submit "Search Spotify", class: "btn btn-primary" %>
          <% end %>
          <%= button_tag 'Add Album not on Spotify', class: 'btn btn-primary floated-left', id: 'add-custom-album-button' %>
        </div>
      </span>
      <span id='add-custom-album' class='hide-this'>
        <div class="modal-body">
          <div class='form-group search-spotify'>
            <%= form_for @collection.albums.new, url: create_custom_collection_albums_path(@collection), remote: true, method: :post do |f| %>
              <%= f.text_field :name, class: "form-control", placeholder: 'Album Name' %>
              <%= f.text_field :artist, class: "form-control", placeholder: 'Artist Name' %>
              <%= f.select :year, options_for_select(1920..(Date.today.year + 1), Date.today.year), {}, class: "form-control", placeholder: 'Year of Release' %>
          </div>
        </div>
        <div class="modal-footer">
            <%= f.submit "Create Album", class: "btn btn-primary" %>
          <% end %>
          <%= button_tag 'Add Album from Spotify', class: 'btn btn-primary floated-left', id: 'search-spotify-button' %>
        </div>
      </span>
    </div>
  </div>
</div>

<script>
  $('#add-custom-album-button').on('click', function() {
    $('#search-spotify').addClass('hide-this');
    $('#add-custom-album').removeClass('hide-this');
  });

  $('#search-spotify-button').on('click', function() {
    $('#add-custom-album').addClass('hide-this');
    $('#search-spotify').removeClass('hide-this');
  });
</script>

app/views/collections/_edit_model.html.erb
<div class="modal fade" id="edit-collection">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Edit collection settings</h4>
      </div>
      <div class="modal-body">
        <div class='form-group'>
          <%= form_for @collection, url: collection_path(@collection), method: :patch do |f| %>
            <%= f.text_field :title, class: "form-control", placeholder: 'Title', id: 'edit_collection_title' %>
            <div class='order-toggle'>
              <%= f.check_box :ordered, 'data-toggle' => 'toggle', 'data-on' => 'Yes', 'data-off' => 'No', 'data-onstyle' => 'success', 'data-offstyle' => 'danger' %>
              <%= f.label :ordered, "Order collection?", { class: "checkbox inline" } %>
            </div>
        </div>
      </div>
      <div class="modal-footer">
          <%= f.submit 'Update', class: "btn btn-primary update-collection-button" %>
        <% end %>
        <%= button_to 'Delete Collection', collection_path(@collection), method: :delete, class: 'btn btn-danger floated-left' %>
      </div>
    </div>
  </div>
</div>

app/views/collections/_preview.html.erb
<% art = collection.albums.where('art IS NOT NULL').pluck(:art) %>
<% if art.count >= 9 %>
  <% 3.times do %>
    <div class='row nopadding'>
      <% 3.times do %>
        <div class='col-xs-4 nopadding'>
          <img class='album-preview' src=<%= art.delete_at(rand(art.length)) %>>
        </div>
      <% end %>
    </div>
  <% end %>
<% elsif art.count >= 4 %>
  <% 2.times do %>
    <div class='row nopadding'>
      <% 2.times do %>
        <div class='col-xs-6 nopadding'>
          <img class='album-preview' src=<%= art.delete_at(rand(art.length)) %>>
        </div>
      <% end %>
    </div>
  <% end %>
<% elsif art.count >= 1 %>
  <div class='row nopadding'>
    <div class='col-xs-12 nopadding'>
      <img class='album-preview' src=<%= art.delete_at(rand(art.length)) %>>
    </div>
  </div>
<% elsif art.empty? %>
  <div class='row nopadding'>
    <div class='col-xs-12 nopadding'>
      <%= image_tag 'empty-collection.png', class: 'album-preview' %>
    </div>
  </div>
<% end %>

app/views/collections/_reorder_script.html.erb
<script>
  $("#collection").sortable({
    items: ".album-wrapper",
    handle: ".order",
    opacity: 0.6,
    update: function() {
      sendOrderToServer();
    }
  });

  $(".order").hover(
    function() {
      $(this).css("cursor", "move");
    }, function() {
      $(this).css("cursor", "");
    }
  );

  function sendOrderToServer() {
    var order = $("#collection").sortable("serialize");
    var url = $("#collection").data("reorder-path");

    $.ajax({
      type: "POST",
      dataType: "json",
      url: url,
      data: order,
      success: function(response) {
        $(".order").each(function(index, value) {
          var new_position = (index + 1)
          $(this).replaceWith("<div class='order'><h3>" + new_position + "</h3></div>");
        });
      }
    });
  }
</script>

app/views/collections/_share_model.html.erb
<div class="modal fade" id="share-collection">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Share Tapedeck</h4>
      </div>
      <div class="modal-body">

        <div class='share-url'>
          <h5><%= collection_url(@collection) %></h5>
        </div>

        <div class='share-button'>
          <div class="fb-share-button" data-href="<%= collection_url(@collection) %>" data-layout="button" data-size="large" data-mobile-iframe="true"><a class="fb-xfbml-parse-ignore" target="_blank" href="">Share</a></div>
        </div>

        <div class='share-button'>
          <a href="https://twitter.com/share" class="twitter-share-button" data-text="<%= @collection.title %>" data-show-count="false" data-size="large">Tweet</a>
          <script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>
        </div>

        <div>
          <h5><%= fa_icon 'instagram' %> Instagram (screenshot this image, reload to regenerate)</h5>
          <%= render 'collections/preview', collection: @collection %>
        </div>
      </div>
    </div>
  </div>
</div>

<script>
  (function(d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
    js = d.createElement(s); js.id = id;
    js.src = "//connect.facebook.net/en_GB/sdk.js#xfbml=1&version=v2.8&appId=1114531281974828";
    fjs.parentNode.insertBefore(js, fjs);
  }(document, 'script', 'facebook-jssdk'));
</script>

app/views/collections/edit.html.erb
<div class="row top-margin-lg bottom-margin-lg">
  <div class="col-xs-2"></div>
  <div class="col-xs-8">
    <h1 class='center-align'><%= @collection.title %></h1>
    <p class='col-xs-12'>
      <div class='col-xs-4 center-align'>
        <span data-toggle="modal" data-target="#new-tape" class='right-align clickable underline'>
          <%= fa_icon 'plus' %> add tape
        </span>
      </div>
      <div class='col-xs-4 center-align'>
        <span data-toggle="modal" data-target="#edit-collection" class='right-align clickable underline'>
          <%= fa_icon 'wrench' %> settings
        </span>
      </div>
      <div class='col-xs-4 center-align'>
        <span class='underline'><%= fa_icon 'bolt' %> <%= link_to 'finish', collection_path(@collection) %></span>
      </div>
    </p>
  </div>
  <div class="col-xs-2"></div>
</div>
<div id='collection' class="row row-centered bottom-margin-lg" data-reorder-path="<%= collection_reorder_path(@collection) %>">
  <%= render @collection.albums.order('position'), collection: @collection, edit: true %>
</div>

<% if @collection.ordered? %>
  <div id='reorder-script'>
    <%= render 'collections/reorder_script' %>
  </div>
<% end %>

<%= render 'collections/add_model' %>
<%= render 'collections/edit_model' %>

app/views/collections/show.html.erb
<div class="row top-margin-lg bottom-margin-lg">
  <div class="col-xs-3"></div>
  <div class="col-xs-6">
    <h1 class='center-align'><%= @collection.title %></h1>
    <p class='center-align'>
      <% if user_signed_in? && current_user.can_edit_collection?(@collection) %>
        Curated by <span class='underline'><%= link_to 'you', user_path(@collection.user) %></span> (<span class='underline'><%= link_to 'edit', edit_collection_path(@collection) %></span>)
      <% else %>
        Curated by <span class='underline'><%= link_to @collection.user.username, user_path(@collection.user) %></span>
      <% end %>
    </p>
  </div>
  <div class="col-xs-1"></div>
  <div class="col-xs-1 center-align">
    <span data-toggle="modal" data-target="#share-collection" class='clickable'>
      <%= fa_icon 'bullhorn' %></br>Share
    </span>
  </div>
  <div class="col-xs-1"></div>
</div>
<div id='collection' class="row row-centered bottom-margin-lg" data-reorder-path="<%= collection_reorder_path(@collection) %>">
  <%= render @collection.albums.order('position'), collection: @collection %>
</div>

<%= render 'collections/share_model' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tapedeck</title>
    <%= csrf_meta_tags %>

    <%= favicon_link_tag 'favicon.png' %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <div class='container'>

      <%= yield %>

      <nav class="navbar navbar-fixed-bottom navbar-light bg-faded cd-auto-hide-header">
        <div class='col-xs-3 nopadding'>
          <%= render 'shared/player' %>
        </div>
        <div class='col-xs-6'>
        </div>
        <div class='col-xs-3 nopadding'>
          <div class="btn-group dropup" id='menu-wrapper'>
            <button type="button" id='menu-button' class="btn btn-default" data-toggle="dropdown">
              <%= image_tag 'icon.png', size: '70x70' %>
            </button>
            <ul class="dropdown-menu dropdown-menu-right" id='menu'>
              <%= link_to collections_path, method: :post do %>
                <li id='menu-item-create' class='menu-item'>
                  <div class='menu-item-icon'>
                    <h3><%= fa_icon 'bolt' %></h3>
                  </div>
                  <div class='menu-item-text'>
                    <h3>Create</h3>
                  </div>
                </li>
              <% end %>
              <% if user_signed_in? %>
                <%= link_to user_path(current_user) do %>
                  <li id='menu-item-profile' class='menu-item'>
                    <div class='menu-item-icon'>
                      <h3><%= fa_icon 'user' %></h3>
                    </div>
                    <div class='menu-item-text'>
                      <h3>Profile</h3>
                    </div>
                  </li>
                <% end %>
              <% end %>
              <%= link_to random_collections_path do %>
                <li id='menu-item-random' class='menu-item'>
                  <div class='menu-item-icon'>
                    <h3><%= fa_icon 'random' %></h3>
                  </div>
                  <div class='menu-item-text'>
                    <h3>Random</h3>
                  </div>
                </li>
              <% end %>
              <%= link_to root_url do %>
                <li id='menu-item-about' class='menu-item'>
                  <div class='menu-item-icon'>
                    <h3><%= fa_icon 'question-circle-o' %></h3>
                  </div>
                  <div class='menu-item-text'>
                    <h3>About</h3>
                  </div>
                </li>
              <% end %>
              <% if user_signed_in? %>
                <%= link_to destroy_user_session_path, method: :delete do %>
                  <li id='menu-item-sign-out' class='menu-item'>
                    <div class='menu-item-icon'>
                      <h3><%= fa_icon 'sign-out' %></h3>
                    </div>
                    <div class='menu-item-text'>
                      <h3>Sign Out</h3>
                    </div>
                  </li>
                <% end %>
              <% else %>
                <%= link_to new_user_session_path do %>
                  <li id='menu-item-sign-in' class='menu-item'>
                    <div class='menu-item-icon'>
                      <h3><%= fa_icon 'sign-in' %></h3>
                    </div>
                    <div class='menu-item-text'>
                      <h3>Sign In</h3>
                    </div>
                  </li>
                <% end %>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </div>
  </body>
</html>

app/views/shared/_create_button.html.erb
<h4 data-toggle="modal" data-target="#new-collection" class='clickable'>
  <%= fa_icon 'bolt' %> Create
</h4>

<div class="modal fade" id="new-collection">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Modal title</h4>
      </div>
      <div class="modal-body">
        <%= form_for Collection.new, url: collections_path do |f| %>
          <%= f.label :title %>
          <%= f.text_field :title %>
      </div>
      <div class="modal-footer">
          <%= f.submit class: "btn btn-primary" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_player.html.erb
<div id="player" class='slider'>
  <div id="player_cover"></div>
  <div id="player_info">
    <div id="player_song"></div>
    <div id="player_artist"></div>
    <div id="player_album"></div>
  </div>
  <div id="player_controls">
    <%= fa_icon 'step-forward', class: 'next_button clickable', id: 'next_button' %>
    <%= fa_icon 'stop', class: 'stop_button clickable', id: 'stop_button' %>
    <%= fa_icon 'step-backward', class: 'previous_button clickable', id: 'previous_button' %>
  </div>
</div>

<div id='jplayer1'>
</div>

<div id='jplayer2'>
</div>

app/views/spotify/_results.html.erb
<div class='container'>
  <% if @albums.any? %>
    <% @albums.each do |album| %>
      <div class='nopadding col-xs-3'>
        <%= link_to collection_albums_path(@collection, spotify_id: album.spotify_id), method: :post, remote: true do %>
          <img class="album img-thumbnail" src=<%= album.art %>>
        <% end %>
      </div>
    <% end %>
  <% else %>
    None found!
  <% end %>
</div>

app/views/spotify/index.html.erb
<%= form_for :spotify, url: search_spotify_index_path, remote: true do |f| %>
  <%= f.text_field :query %>
  <%= f.submit %>
<% end %>

<div id='results'>
</div>

<div id='jplayer1'>
</div>

<div id='jplayer2'>
</div>

app/views/spotify/search.js.erb
$('#results').html("<%= j render 'spotify/results' %>");

app/views/users/show.html.erb
<div class="row top-margin-lg bottom-margin-lg">
  <div class="col-xs-3"></div>
  <div class="col-xs-6">
    <h1 class='center-align'><%= @user.username %></h1>
  </div>
  <div class="col-xs-3"></div>
</div>
<div id="user-collections" class='bottom-margin-lg'>
  <div class='row row-centered'>
    <% if @user.collections.any? %>
      <% @user.collections.order('created_at DESC').each do |collection| %>
        <div class='collection-preview-wrapper col-centered col-xs-6 col-sm-3'>
          <%= link_to collection_path(collection) do %>
            <div class='collection-preview'>
              <%= render 'collections/preview', collection: collection %>
            </div>
          <% end %>
          <div class='collection-preview-title'>
            <%= link_to collection_path(collection) do %>
              <h4><%= collection.title %></h4>
            <% end %>
            <% if collection.albums.empty? %>
              (<%= link_to 'delete', collection_path(collection), method: :delete %>)
            <% end %>
          </div>
        </div>
      <% end %>
    <% else %>
      <h3>You have no collections yet. <%= link_to 'Create one', collections_path, class: 'underline', method: :post %>.</h3>
    <% end %>
  </div>
</div>

app/views/welcome/about.html.erb
<div id='about'>
  <div class='row'>
    <div class='col-xs-12 top-margin-lg'>
      <h3>Create and share lists of your favourite records.</h3>
      <h6>Tapedeck is free and <span class='underline'><a href='https://github.com/cjbutcher/tapedeck-2' target='_blank'>open-source!</a></span> 😄</h6>
    </div>
    <div class='col-xs-12'>
      <%= button_to 'Show me an example', random_collections_path, class: 'btn btn-primary', id: 'show-me-button', method: :get %>
    </div>
    <div class='col-xs-12 bottom-margin-lg'>
      <p><b>Shortcuts</b></p>
      <p><b>r</b> random Tapedeck.</p>
      <p><b>c</b> create a Tapedeck.</p>
      <p><b>space</b> stop music.</p>
      <p><b>]</b> next track.</p>
      <p><b>[</b> previous track.</p></br>
      <p>Click <%= image_tag 'icon.png', size: '20x20' %> in the bottom right for a menu.</p>
    </div>
  </div>
</div>